adds test that reproduces the ` reactor.core.Exceptions$OverflowException`
rsocket/rsocket-java pull request #985
Opened 2021-02-22 10:16 UTC by OlegDokuka

closes #959 

Some fix details:

Due to the RSocket Specification, section ["Handling the unexpected"](https://github.com/rsocket/rsocket/blob/master/Protocol.md#handling-the-unexpected)

> Lack of REQUEST_N frames that stops a stream is an application concern and SHALL NOT be handled by the protocol.

the `RequestOperator` does unbounded request to the `UnicastProcessor` once in order to avoid any concurrency on the internal WIP field.

Signed-off-by: Oleh Dokuka <shadowgun@i.ua>

2021-02-22 10:21 UTC, OlegDokuka commented
pointers to the failed test -> https://travis-ci.org/github/rsocket/rsocket-java/jobs/759973034 with the mentioned exception in the original issue

2021-02-22 11:21 UTC, rstoyanchev requested changes
Looks good as a tactical solution in 1.0.x for now, although eventually it should be replaced with the queue-free and WIP-free UnicstProcessor you mentioned in https://github.com/rsocket/rsocket-java/issues/959#issuecomment-782010649.

2021-02-22 11:21 UTC, rstoyanchev commented on rsocket-core/src/main/java/io/rsocket/core/RequestOperator.java
> +          this.s.request(Long.MAX_VALUE);
An implementation comment on here would be helpful I think as it is not obvious. Some condensed summary of https://github.com/rsocket/rsocket-java/issues/959#issuecomment-782025770 also mentioning that the queue in `UnicastProcessor` is of size 1.

2021-02-25 15:13 UTC, rstoyanchev approved these changes

2021-02-25 15:15 UTC, merged